// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "Receiver.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using namespace  ::dcma::rpc;

class ReceiverHandler : virtual public ReceiverIf {
 public:
  ReceiverHandler() {
    // Your initialization goes here
  }

  void GetSupportedOperations(std::vector<KnownOperation> & _return, const OperationsQuery& query) {
    // Your implementation goes here
    printf("GetSupportedOperations\n");
  }

  void LoadFiles(LoadFilesResponse& _return, const std::vector<LoadFilesQuery> & server_filenames) {
    // Your implementation goes here
    printf("LoadFiles\n");
  }

  void ExecuteScript(ExecuteScriptResponse& _return, const ExecuteScriptQuery& query, const std::string& script) {
    // Your implementation goes here
    printf("ExecuteScript\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  ::std::shared_ptr<ReceiverHandler> handler(new ReceiverHandler());
  ::std::shared_ptr<TProcessor> processor(new ReceiverProcessor(handler));
  ::std::shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  ::std::shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  ::std::shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

