//Structs_IO_Protobufs.cc.

#include <cmath>
#include <map>
#include <unordered_map>
#include <cstdint>   //For int64_t.
#include <utility>   //For std::pair.
#include <algorithm> //std::min_element/max_element, std::stable_sort.
#include <tuple>
#include <array>
#include <functional>

#include "YgorMisc.h"
#include "YgorMath.h"
#include "YgorImages.h"

#include "Serialization.pb.h" //Is generated by the protocol buffer compiler. 

#include "Structs.h"
#include "Structs_IO_Protobufs.h"


bool from_protobuf(vec3<double> &lhs, Vec3DoubleMsg &rhs){
    lhs.x = rhs.x();   
    lhs.y = rhs.y();   
    lhs.z = rhs.z();   
    return true;
}

bool to_protobuf(vec3<double> &lhs, Vec3DoubleMsg &rhs){
    rhs.set_x(lhs.x);
    rhs.set_y(lhs.y);
    rhs.set_z(lhs.z);
    return true;
}




