//Structs_IO_Protobufs.h.
#pragma once

#include <cmath>
#include <map>
#include <unordered_map>
#include <cstdint>   //For int64_t.
#include <utility>   //For std::pair.
#include <algorithm> //std::min_element/max_element, std::stable_sort.
#include <tuple>
#include <array>
#include <functional>

#include "YgorMisc.h"
#include "YgorMath.h"
#include "YgorImages.h"

#include "Serialization.pb.h" //Is generated by the protocol buffer compiler. 

#include "Structs.h"


bool from_protobuf(vec3<double> &, Vec3DoubleMsg &);
bool to_protobuf(vec3<double> &, Vec3DoubleMsg &);


// ... fill in the remaining routines for the other types.

